### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [jorgecasar/payment-request#1]
Demo doesn't work. Tested on Google Chrome 59.0.3070.4 for Android.

**Comment by FluorescentHallucinogen** [comment]
P.S. The demo doesn't work on https://www.webcomponents.org/element/jorgecasar/payment-request/demo/demo/index.html and https://jorgecasar.github.io/payment-request/components/payment-request/ pages, but works on https://jorgecasar.github.io/payment-request/components/payment-request/demo/ page.

**Comment by FluorescentHallucinogen** [comment]
Seems the problem is in using iframes.

Starting with Chrome 57, using the Payment Request API inside an iframe is supported. Simply add `allowpaymentrequest` attribute to allow the iframe to use the API.

```html
<iframe src="URL_INCLUDING_PAYMENT_REQUEST_CALL" allowpaymentrequest></iframe>
```

**Comment by jorgecasar** [comment]
I've just update including shipping and I guess this is solved.

Let's me know if I can close it.

**Comment by FluorescentHallucinogen** [comment]
This is not solved. Open https://www.webcomponents.org/element/jorgecasar/payment-request/demo/demo/index.html or https://jorgecasar.github.io/payment-request/components/payment-request/ and tap "Pay" button.

But I've found that "Overview" block on https://webcomponents.org/element/jorgecasar/payment-request page is now empty. See screenshots.

Before:

![before](https://cloud.githubusercontent.com/assets/7892779/25302813/906f6df6-274f-11e7-9073-858734423d35.png)

After:

![after](https://cloud.githubusercontent.com/assets/7892779/25302814/9694b18c-274f-11e7-84f3-395b7f2dd69e.png)

**Comment by jorgecasar** [comment]
I don't know how webcomponents.org get this links. In the gh-pages it's all right: https://jorgecasar.github.io/payment-request/components/payment-request/

**Comment by FluorescentHallucinogen** [comment]
Maybe @samuelli knows?

**Comment by jorgecasar** [comment]
Reading the Webcomponents.org code I found how.

https://github.com/webcomponents/webcomponents.org/blob/c832fd05b0e958731bddc6f6226de8c679ac43f5/src/api.py#L200-L205

Let's me try ;)

**Comment by jorgecasar** [comment]
I tried several things and the pattern is that the request to /api/docs/<owner>/<repo> return an 400 error (https://www.webcomponents.org/api/docs/jorgecasar/payment-request?) because the analysis doesn't return a status ready (https://github.com/webcomponents/webcomponents.org/blob/master/src/api.py#L363)

@samuelli can you help with this?

**Comment by samuelli** [comment]
Hi @jorgecasar,

See https://github.com/jorgecasar/payment-request/blob/master/bower.json#L5

:)

**Comment by jorgecasar** [comment]
@samuelli I fix it but it doesn't appear. This is the preview of the commit that fix it: https://www.webcomponents.org/preview/jorgecasar/payment-request/5958399a3f1bdf76fd76b8a116ec81f670d4c9af

**Comment by samuelli** [comment]
Sorry for taking a while to take a look. I thought it may have been related to a separate issue we were seeing but its not.

Seems that its failing to find some dependencies. eg. https://github.com/jorgecasar/payment-request/blob/master/payment-request.html#L2 is not specified in your bower dependencies but still imported. Best to check all your imports/dependencies and try again.

**Comment by jorgecasar** [comment]
Thanks @samuelli!

Now it's working ;)
